### ISSUE TITLE
links on support site not working

### ISSUE THREAD

**Issue by Dominik-K** [ZotPlus/ZotPlus.github.io#1]
On https://zotplus.github.io/support.html , all the links to the issues site of your ZotPlus plugins don't work.

BTW: The link to "guidelines for contributing" on the Better Bib(La)TeX new issue site links to 
https://github.com/ZotPlus/zotero-better-bibtex/blob/master/CONTRIBUTING.md
instead of 
https://github.com/ZotPlus/ZotPlus.github.io/blob/master/support.md

Moved from https://github.com/ZotPlus/zotero-better-bibtex/issues/223

**Comment by retorquere** [comment]
Thanks for the report. Unfortunately, I can't link to https://github.com/ZotPlus/ZotPlus.github.io/blob/master/support.md; only if a file named CONTRIBUTING.md is present in the root of the repo, the link to it shows up in the issues list

**Comment by Dominik-K** [comment]
Oh, I see. So, how about just putting a link inside CONTRIBUTING.md to the support.md? Submoduling a file doesn't work, right?

**Comment by retorquere** [comment]
Wish I could, but no. I'd rather not have people have to click-through to get at the information. I might work up a script to make it automatic though.

**Comment by Dominik-K** [comment]
Hmm, ok. I meant it just as a suggestion that you don't have to update all the project CONTRIBUTING.md's as well if you change support.md But a script can do this work, too ;-)
The links on the support website are working. So I'm closing the issue.
